language: node_js #语言

sudo: false #禁用sudo权限

cache:
  apt: true #开启缓存
  directories: #缓存目录
    - node_modules

node_js: stable #使用的node.js版本

install: #安装的依赖
  - npm install -D #安装构建器的依赖
  - cd ./test/smoke/template #修改当前的工作目录
  - npm install -D #安装模板项目的依赖
  - cd ../../../ #返回到根目录

scripts:
  - npm test #运行测试 nyc ./node_modules/.bin/_mocha